stages:
  - build
  - deploy

build:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker-compose -f docker-compose.yml pull
    - docker-compose -f docker-compose.yml config -q
  only:
    - main

deploy:
  stage: deploy
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker-compose -f docker-compose.yml pull
    - docker-compose -f docker-compose.yml up -d --build
  only:
    - main
